[project]
name = "youtube-video-transcription"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openai",
    "yt-dlp",
    "torch",
    "torchaudio",
    "openai-whisper",
    "python-dotenv>=1.0.1",
]
